[package]
name = "malakai/notsureyet"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.4.4"
Component = "sleitnick/component@2.4.4"
Signal = "sleitnick/signal@1.1.0"
Trove = "sleitnick/trove@0.3.0"
Input = "sleitnick/input@1.3.2"
Shake = "sleitnick/shake@0.1.4"
TableUtil = "sleitnick/table-util@1.1.1"
Janitor = "howmanysmall/janitor@1.13.15"